create table contacts(
  id int generated by default as identity,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(255) not null,
  phone varchar(15),
  primary key (id)
);

insert into contacts(first_name, last_name, email, phone)
values ('John', 'Doe', 'john.doe@example.com', NULL),
       ('Lily', 'Bush', 'lily.bush@example.com', '(408-234-2764)');

